### ISSUE TITLE
Generated parser with simple rule

### ISSUE THREAD

**Issue by gligneul** [vsbenas/parser-gen#1]
Hello,

I'm using parser-gen and I found an odd behaviour. I was able to reduce the problem to this simple grammar:

    top <- foo 'bar' !.
    foo <- 'foo' 'foo' / 'foo'

The generated parser is not able to parse the string "foo bar", it expects another foo, even though it isn't necessary.
I'm able to work around this issue by inlining the rule:

    top <- ('foo' 'foo' / 'foo') 'bar' !.

The full code snipet to reproduce the issue:

    local pg = require 'parser-gen'
    local peg = require 'peg-parser'
    
    local grammar = pg.compile([[
    
        top     <- foo 'bar' !.
    
        foo     <- (('foo' 'foo') / 'foo')
    
    ]], _, true)
    
    local function printerror(desc, line, col, sfail, trec)
        print('Error: ' .. desc .. ' on line ' .. line ..
              ' (col ' .. col .. ')')
    end
    
    local input = [[
    foo bar
    ]]
    
    local result = pg.parse(input, grammar, printerror)
    peg.print_t(result)

Regards,
Gabriel

**Comment by vsbenas** [comment]
Hey,

Thanks for the report.
The error generation only works for LL(1) grammars. Your grammar is not
LL(1) and error generation is enabled (in the compile function) so it
produces an invalid output.

Hopefully in the future I will be able to update the error generation to
support all grammars.

Actually, I should remove the experimental error generation feature from the full example... Thanks!

**Comment by gligneul** [comment]
Thanks for the fast response.
It worked flawlessly without the error generation.
