### ISSUE TITLE
Tag v1.1 still on commit with <<< >>> merge artifacts

### ISSUE THREAD

**Issue by FilWisher** [vsbenas/parser-gen#11]
Hey, thanks for this module!

The commit that v1.1 is on (which is pointed to by the 1.1-0.rockspec) still contains the git merge artifacts that have now been removed.

Either the tag should be moved to exclude the artifacts or new tags and a new rockspec version.

I'm happy to do this if you don't have time

**Comment by jirutka** [comment]
Release tags should be NEVER moved! The only correct solution is to tag and release a new version (bump patch (3rd) number, in terms of semver).

**Comment by vsbenas** [comment]
Thanks! I made a new release.

**Comment by FilWisher** [comment]
Thank you
