### ISSUE TITLE
parser-gen is creating a bunch of global variables

### ISSUE THREAD

**Issue by hugomg** [vsbenas/parser-gen#7]
Currently, requiring parser-gen is polluting the global scope with many global functions. These should all be made local and exported in the return statement if needed. The ones I managed to find were:

* In equals.lua: `equals`
* In errorgen.lua: `getn`
* In parser-gen.lua: `traverse`, `record`, `recorderror`
* In peg-parser.lua: `concat`, `foldtable`
* In stack.lua: `Stack`

**Comment by vsbenas** [comment]
Thanks for pointing those out, all fixed in the latest commit.
